USE ROLE SYSADMIN;

CREATE WAREHOUSE IF NOT EXISTS NYC311_WH
  WAREHOUSE_SIZE = 'XSMALL'
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE;

CREATE DATABASE IF NOT EXISTS NYC311;
CREATE SCHEMA IF NOT EXISTS NYC311.RAW;

CREATE TABLE IF NOT EXISTS NYC311.RAW.SERVICE_REQUESTS (
  raw_data     VARIANT,
  source_file  STRING,
  loaded_at    TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

USE WAREHOUSE NYC311_WH;
