USE ROLE ACCOUNTADMIN;
GRANT USAGE ON INTEGRATION NYC311_S3_INT TO ROLE SYSADMIN;

USE ROLE SYSADMIN;
USE WAREHOUSE NYC311_WH;
USE SCHEMA NYC311.RAW;

CREATE FILE FORMAT IF NOT EXISTS JSON_FMT
  TYPE = JSON
  STRIP_OUTER_ARRAY = TRUE;

CREATE STAGE IF NOT EXISTS NYC311_S3_STAGE
  URL = 's3://<YOUR_BUCKET>/landing/'
  STORAGE_INTEGRATION = NYC311_S3_INT
  FILE_FORMAT = JSON_FMT;

LIST @NYC311_S3_STAGE;

COPY INTO SERVICE_REQUESTS (raw_data, source_file)
  FROM (SELECT $1, METADATA$FILENAME FROM @NYC311_S3_STAGE);

-- Sanity checks
SELECT COUNT(*), COUNT(DISTINCT raw_data:unique_key) FROM SERVICE_REQUESTS;

SELECT raw_data:complaint_type::STRING AS complaint_type, COUNT(*) AS n
FROM SERVICE_REQUESTS
GROUP BY 1
ORDER BY 2 DESC;
