-- Least-privilege loader role + key-pair service user for Airflow
USE ROLE SECURITYADMIN;
CREATE ROLE IF NOT EXISTS PIPELINE_LOADER;
GRANT ROLE PIPELINE_LOADER TO ROLE SYSADMIN;

USE ROLE SYSADMIN;
GRANT USAGE ON WAREHOUSE NYC311_WH TO ROLE PIPELINE_LOADER;
GRANT USAGE ON DATABASE NYC311 TO ROLE PIPELINE_LOADER;
GRANT USAGE ON SCHEMA NYC311.RAW TO ROLE PIPELINE_LOADER;
GRANT USAGE ON STAGE NYC311.RAW.NYC311_S3_STAGE TO ROLE PIPELINE_LOADER;
GRANT USAGE ON FILE FORMAT NYC311.RAW.JSON_FMT TO ROLE PIPELINE_LOADER;
GRANT SELECT, INSERT ON TABLE NYC311.RAW.SERVICE_REQUESTS TO ROLE PIPELINE_LOADER;

USE ROLE SECURITYADMIN;
CREATE USER IF NOT EXISTS AIRFLOW_SVC
  TYPE = SERVICE
  DEFAULT_ROLE = PIPELINE_LOADER
  DEFAULT_WAREHOUSE = NYC311_WH;
-- Public key only; the private key stays on the host in ~/.snowflake
ALTER USER AIRFLOW_SVC SET RSA_PUBLIC_KEY = '<RSA_PUBLIC_KEY>';
GRANT ROLE PIPELINE_LOADER TO USER AIRFLOW_SVC;
