x-local-creds: &local-creds
  volumes:
    - ${HOME}/.aws:/usr/local/airflow/.aws:ro
    - ${HOME}/.snowflake:/usr/local/airflow/.snowflake:ro

services:
  scheduler: *local-creds
  api-server: *local-creds
  dag-processor: *local-creds
  triggerer: *local-creds
